name: Deploy Laravel to Server

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export PATH=$PATH:/usr/local/bin:~/.nvm/versions/node/$(ls ~/.nvm/versions/node 2>/dev/null | tail -n 1)/bin
            cd /www/wwwroot/petitemucost.hanmeini.my.id
            
            # Ambil alih kepemilikan agar CI/CD bisa jalan
            sudo chown -R $(whoami):$(whoami) .
            
            git config --global --add safe.directory /www/wwwroot/petitemucost.hanmeini.my.id
            git pull origin ${{ github.ref_name }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            npm install
            npm run build
            
            # Kembalikan kepemilikan ke web server agar web tidak error 500
            sudo chown -R www:www .
